Content:
    - framework/doc/content
    - modules/rdg/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE rDG Module
    repo: https://github.com/idaholab/moose
    home: /documentation/modules/rdg

Extensions:
    appsyntax:
        type: MooseDocs.extensions.appsyntax
        executable: ${MOOSE_DIR}/modules/rdg
        hide: !include framework/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/rdg/include
    globals:
        type: MooseDocs.extensions.panoptic
        shortcuts: !include framework/doc/globals.yml
