# Generated by YCM Generator at 2018-02-22 11:00:03.701811

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-DCHEMICAL_REACTIONS_ENABLED',
    '-DCOMBINED_ENABLED',
    '-DCONTACT_ENABLED',
    '-DFLUID_PROPERTIES_ENABLED',
    '-DFUNCTIONAL_EXPANSION_TOOLS_ENABLED',
    '-DHEAT_CONDUCTION_ENABLED',
    '-DLEVEL_SET_ENABLED',
    '-DMETHOD=opt',
    '-DMISC_ENABLED',
    '-DNAVIER_STOKES_ENABLED',
    '-DNDEBUG',
    '-DPHASE_FIELD_ENABLED',
    '-DPIC',
    '-DPOROUS_FLOW_ENABLED',
    '-DRDG_ENABLED',
    '-DRICHARDS_ENABLED',
    '-DSOLID_MECHANICS_ENABLED',
    '-DSTOCHASTIC_TOOLS_ENABLED',
    '-DTENSOR_MECHANICS_ENABLED',
    '-DWATER_STEAM_EOS_ENABLED',
    '-DXFEM_ENABLED',
    '-D_THREAD_SAFE',
    '-I/Users/kothari/MOOSE_ICS/moose-DNDEBUG',
    '-I/Users/kothari/MOOSE_ICS/moose/PorousFlowSingleComponentFluid.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/SwitchingFunctionMultiPhaseMaterial.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framew-DNDEBUG',
    '-I/Users/kothari/MOOSE_ICS/moose/framew/NSMomentumViscousFlux.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framew/modules/tensor_mechanics/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/framewdBodyModes3D.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framewels/NSPressureAux.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framewobjects/CO2FluidProperties.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/boost/include',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/gtest',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/hit',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/jsoncpp/include',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/jsoncpp/include/json',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/mtwist/include',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/pcre/include',
    '-I/Users/kothari/MOOSE_ICS/moose/framework/contrib/tinydir/include',
    '-I/Users/kothari/MOOSE_ICS/moose/framewplitCHWResAniso.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framewts/MaskedGrainForceAndTorque.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/framewwitchingFunctionConstraintEta.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/chemical_reactions/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/combined/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/contact/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/fluid_properties/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/functional_expansion_tools/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/heat_conduction/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/level_set/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/misc/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/navier_stokes/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/phase_field/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/porous_flow/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/rdg/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/richards/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/solid_mechanics/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/stochastic_tools/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/tensor_mechanics/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/water_steam_eos/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/modules/xfem/build/header_symlinks',
    '-I/Users/kothari/MOOSE_ICS/moose/scripts/../libmesh/installed/include',
    '-I/Users/kothari/MOOSE_ICS/moose4-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/mooseRichardsSUPGstandard.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moose_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/mooseangevinNoise.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/moosearPeriodicMesh.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/mooseatAnisoDiffusion.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/Users/kothari/MOOSE_ICS/mooseork/contrib/tinydir/include',
    '-I/Users/kothari/MOOSE_ICS/mooseorousFlowEffectiveStressCoupling.x86_64-apple-darwin17.4.0.opt.lo.d',
    '-I/opt/X11/include',
    '-I/opt/moose/mpich-3.2/clang-5.0.0/include',
    '-I/opt/moose/petsc-3.7.6/mpich-3.2_clang-5.0.0-opt//include',
    '-I/opt/moose/petsc-3.7.6/mpich-3.2_clang-5.0.0-opt/include',
    '-Werror=reorder',
    '-Werror=return-type',
    '-Woverlength-strings',
    '-Wunused',
    '-Wunused-parameter',
    '-install_name',
    '-std=gnu++11',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

