Content:
    - framework/doc/content
    - modules/water_steam_eos/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Water Steam EOS Module
    repo: https://github.com/idaholab/moose
    home: /documentation/modules/water_steam_eos

Extensions:
    appsyntax:
        type: MooseDocs.extensions.appsyntax
        executable: ${MOOSE_DIR}/modules/water_steam_eos
        hide: !include framework/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/water_steam_eos/include
    globals:
        type: MooseDocs.extensions.panoptic
        shortcuts: !include framework/doc/globals.yml
    acronyms:
        type: MooseDocs.extensions.acronym
        acronyms: !include framework/doc/acronyms.yml
